

export class Texts{
    FaTexts: { [key: string]: string; }={};
    Texts: { [key: string]: string; }={};

    Init(){
        this.FaTexts["header1"] = "گیمـ"
        this.FaTexts["header2"] = "برنامه زمانی"
        this.FaTexts["header3"] = "کارگاه ها"
        this.FaTexts["header4"] = "تاک ها"
        this.FaTexts["header5"] = "درباره"
        this.FaTexts["header6"] = "ورود"
        this.FaTexts["header7"] = "ثبت نام"
        this.FaTexts["header8"] = "خروج"
        this.FaTexts["header9"] = "داشبورد"
        this.FaTexts["header10"] = "ابولفضل"
        this.FaTexts["header11"] = "شرایط مسابقه"
        this.FaTexts["header12"] = "افراد"

        this.FaTexts["home1"] = "گیمـ"
        this.FaTexts["home2"] = "نهمین رویداد بزرگ بازی سازی درخاورمیانه"
        this.FaTexts["home3"] = "این رویداد در مادر دانشگاه های صنعتی کشور برگذار می شود و خیلی نایس است"
        this.FaTexts["home4"] = "7:23:59:2"
        this.FaTexts["home5"] = "تا شروع رویداد"
        this.FaTexts["home6"] = "2289"
        this.FaTexts["home7"] = "شرکت کننده"
        this.FaTexts["home8"] = "برنامه زمانی"
        this.FaTexts["home9"] = "ثبت نام"
        this.FaTexts["home10"] = "1 بهمن 99"
        this.FaTexts["home11"] = "مسابقه"
        this.FaTexts["home12"] = "11 بهمن 99"
        this.FaTexts["home13"] = "داوری"
        this.FaTexts["home14"] = "21 بهمن 99"
        this.FaTexts["home15"] = "کارگاه ها"
        this.FaTexts["home16"] = "کارگاه بازی سازی"
        this.FaTexts["home17"] = "سه شنبه 2 بهمن 99"
        this.FaTexts["home18"] = "نفر"
        this.FaTexts["home19"] = "مبتدی"
        this.FaTexts["home20"] = "ثبت نام"
        this.FaTexts["home21"] = "توضیحات"
        this.FaTexts["home22"] = " تاریخ بِیهَقی یا تاریخ مسعودی نام کتابی نوشتهٔ ابوالفضل محمد بن حسین بیهقی است که موضوع اصلی آن تاریخ پادشاهی مسعود غزنوی و دودمان غزنوی است. این کتاب علاوه بر تاریخ غزنویان، قسمت‌هایی دربارهٔ صفاریان، سامانیان و دورهٔ پیش از برآمدن و پادشاهی محمود غزنوی دارد. نسخهٔ اصلی کتاب حدود ۳۰ جلد بوده"
        this.FaTexts["home23"] = "ارائه کنندگان"
        this.FaTexts["home24"] = "مسعود فراستی"
        this.FaTexts["home25"] = "منتقد درجه یک"
        this.FaTexts["home26"] = "تاک ها"
        this.FaTexts["home27"] = "گفتگوی کشور ها"
        this.FaTexts["home28"] = "سه شنبه 2 بهمن 99"
        this.FaTexts["home29"] = "نفر"
        this.FaTexts["home30"] = "مبتدی"
        this.FaTexts["home31"] = "ثبت نام"
        this.FaTexts["home32"] = "توضیحات"
        this.FaTexts["home33"] = "تاریخ بِیهَقی یا تاریخ مسعودی نام کتابی نوشتهٔ ابوالفضل محمد بن حسین بیهقی است که موضوع اصلی آن تاریخ پادشاهی مسعود غزنوی و دودمان غزنوی است. این کتاب علاوه بر تاریخ غزنویان، قسمت‌هایی دربارهٔ صفاریان، سامانیان و دورهٔ پیش از برآمدن و پادشاهی محمود غزنوی دارد. نسخهٔ اصلی کتاب حدود ۳۰ جلد بوده"
        this.FaTexts["home34"] = "ارائه کنندگان"
        this.FaTexts["home35"] = "مسعود فراستی"
        this.FaTexts["home36"] = "منتقد درجه یک"
        this.FaTexts["home37"] = "تایتل"
        this.FaTexts["home38"] = "ساب تایتل"
        this.FaTexts["home39"] = "تاریخ بِیهَقی یا تاریخ مسعودی نام کتابی نوشتهٔ ابوالفضل محمد بن حسین بیهقی است که موضوع اصلی آن تاریخ پادشاهی مسعود غزنوی و دودمان غزنوی است. این کتاب علاوه بر تاریخ غزنویان، قسمت‌هایی دربارهٔ صفاریان، سامانیان و دورهٔ پیش از برآمدن و پادشاهی محمود غزنوی دارد. نسخهٔ اصلی کتاب حدود ۳۰ جلد بوده"
        this.FaTexts["home40"] = "حامیان"
        this.FaTexts["home41"] = "حامی"
        this.FaTexts["home42"] = "designed & developed ba eshgh"
        this.FaTexts["home43"] = "جوایز مسابقه"
        this.FaTexts["home44"] = "شرایط مسابقه"
        this.FaTexts["home45"] = "تیم اول"
        this.FaTexts["home46"] = "کارت صد آفرین"
        this.FaTexts["home47"] = "دست اندر کاران"

        this.FaTexts["dash-event1"] = "ابوالفضل بیهقی"
        this.FaTexts["dash-event2"] = "رویداد ها"
        this.FaTexts["dash-event3"] = "محتوا ها"
        this.FaTexts["dash-event4"] = "وضعیت تیم"
        this.FaTexts["dash-event5"] = "افزودن محتوا"
        this.FaTexts["dash-event6"] = "رویداد ها"
        this.FaTexts["dash-event7"] = "کارگاه ها"
        this.FaTexts["dash-event8"] = "کارگاه بازی سازی"
        this.FaTexts["dash-event9"] = "سه شنبه 2 بهمن 99"
        this.FaTexts["dash-event10"] = "11 نفر"
        this.FaTexts["dash-event11"] = "مبتدی"
        this.FaTexts["dash-event12"] = "ثبت نام"
        this.FaTexts["dash-event13"] = "توضیحات"
        this.FaTexts["dash-event14"] = "تاریخ بِیهَقی یا تاریخ مسعودی نام کتابی نوشتهٔ ابوالفضل محمد بن حسین بیهقی است که موضوع اصلی آن تاریخ پادشاهی مسعود غزنوی و دودمان غزنوی است. این کتاب علاوه بر تاریخ غزنویان، قسمت‌هایی دربارهٔ صفاریان، سامانیان و دورهٔ پیش از برآمدن و پادشاهی محمود غزنوی دارد. نسخهٔ اصلی کتاب حدود ۳۰ جلد بوده"
        this.FaTexts["dash-event15"] = "ارائه کنندگان"
        this.FaTexts["dash-event16"] = "مسعود فراستی"
        this.FaTexts["dash-event17"] = "منتقد درجه یک"
        this.FaTexts["dash-event18"] = "تاک ها"
        this.FaTexts["dash-event19"] = "گفتگوی کشور ها"
        this.FaTexts["dash-event20"] = "سه شنبه 2 بهمن 99"
        this.FaTexts["dash-event21"] = "11 نفر"
        this.FaTexts["dash-event22"] = "مبتدی"
        this.FaTexts["dash-event23"] = "ثبت نام"
        this.FaTexts["dash-event24"] = "توضیحات"
        this.FaTexts["dash-event25"] = "تاریخ بِیهَقی یا تاریخ مسعودی نام کتابی نوشتهٔ ابوالفضل محمد بن حسین بیهقی است که موضوع اصلی آن تاریخ پادشاهی مسعود غزنوی و دودمان غزنوی است. این کتاب علاوه بر تاریخ غزنویان، قسمت‌هایی دربارهٔ صفاریان، سامانیان و دورهٔ پیش از برآمدن و پادشاهی محمود غزنوی دارد. نسخهٔ اصلی کتاب حدود ۳۰ جلد بوده"
        this.FaTexts["dash-event26"] = "ارائه کنندگان"
        this.FaTexts["dash-event27"] = "مسعود فراستی"
        this.FaTexts["dash-event28"] = "منتقد درجه یک"
        this.FaTexts["dash-event29"] = "theater_comedy"
        this.FaTexts["dash-event30"] = "perm_media "
        this.FaTexts["dash-event31"] = "groups"
        this.FaTexts["dash-event32"] = "movie"
        this.FaTexts["dash-event33"] = "تیم های رقیب"

        this.FaTexts["error1"] = "error-outline"
        this.FaTexts["error2"] = "deactive"
        this.FaTexts["error3"] = ""

        this.FaTexts["login1"] = "ورود"
        this.FaTexts["login2"] = "گیمـ"
        this.FaTexts["login3"] = "ایمیل"
        this.FaTexts["login4"] = "لطفا یک ایمیل صحیح وارد کنید"
        this.FaTexts["login5"] = "است"
        this.FaTexts["login6"] = "اجباری"
        this.FaTexts["login7"] = "وارد کردن ایمیل"
        this.FaTexts["login8"] = "رمز عبور"
        this.FaTexts["login9"] = "حداقل تعداد کاراکتر های رمز 8 عدد می باشد"
        this.FaTexts["login10"] = "وارد کردن رمز عبور"
        this.FaTexts["login11"] = "ورود"
        this.FaTexts["login12"] = "ثبت نام"
        
        this.FaTexts["signup1"] = "ثبت نام"
        this.FaTexts["signup2"] = "گیمـ"
        this.FaTexts["signup3"] = "نام و نام خانوادگی"
        this.FaTexts["signup4"] = "است"
        this.FaTexts["signup5"] = "اجباری"
        this.FaTexts["signup6"] = "وارد کردن نام"
        this.FaTexts["signup7"] = "ایمیل"
        this.FaTexts["signup8"] = "لطفا یک ایمیل صحیح وارد کنید"
        this.FaTexts["signup9"] = "وارد کردن ایمیل"
        this.FaTexts["signup10"] = "شماره همراه"
        this.FaTexts["signup11"] = "لطفا یک شماره همراه صحیح وارد کنید"
        this.FaTexts["signup12"] = "وارد کردن شماره همراه"
        this.FaTexts["signup13"] = "رمز عبور"
        this.FaTexts["signup14"] = "حداقل تعداد کاراکتر های رمز 8 عدد می باشد"
        this.FaTexts["signup15"] = "وارد کردن رمز عبور"
        this.FaTexts["signup16"] = "ثبت نام"
        this.FaTexts["signup17"] = "ورود"

        this.FaTexts["dash-media1"] = "ابوالفضل بیهقی"
        this.FaTexts["dash-media2"] = "رویداد ها"
        this.FaTexts["dash-media3"] = "محتوا ها"
        this.FaTexts["dash-media4"] = "وضعیت تیم"
        this.FaTexts["dash-media5"] = "افزودن محتوا"
        this.FaTexts["dash-media6"] = "محتوا ها"
        this.FaTexts["dash-media7"] = "کارگاه بازی سازی"
        this.FaTexts["dash-media8"] = "file name"
        this.FaTexts["dash-media9"] = "دانلود"
        this.FaTexts["dash-media10"] = " تاک بازی سازی"
        this.FaTexts["dash-media11"] = "theater_comedy"
        this.FaTexts["dash-media12"] = "perm_media "
        this.FaTexts["dash-media13"] = "groups"
        this.FaTexts["dash-media14"] = "movie"
        this.FaTexts["dash-media15"] = "تیم های رقیب"

        this.FaTexts["people1"] = "افراد"
        this.FaTexts["people2"] = "تیم رنگ کاری"
        this.FaTexts["people3"] = "امیررضا بهمنش"
        this.FaTexts["people4"] = "ستون فرانت"
        this.FaTexts["people5"] = "آرین متقی"
        this.FaTexts["people6"] = "نخودی"
        this.FaTexts["people7"] = "حسین لوک زاده"
        this.FaTexts["people8"] = "ستون بَک"
        this.FaTexts["people9"] = "علیرضا آخوندی"
        this.FaTexts["people10"] = "ستون غایب"
        this.FaTexts["people11"] = "افراد"
        this.FaTexts["people12"] = "افراد"
        this.FaTexts["people13"] = "افراد"
        this.FaTexts["people14"] = "افراد"
        this.FaTexts["people15"] = "افراد"


        this.Texts=this.FaTexts;

    }



}

