

export class Texts{
    FaTexts: { [key: string]: string; }={};
    Texts: { [key: string]: string; }={};

    Init(){
        this.FaTexts["header1"] = "گیمـ"
        this.FaTexts["header2"] = "برنامه زمانی"
        this.FaTexts["header3"] = "کارگاه ها"
        this.FaTexts["header4"] = "تاک ها"
        this.FaTexts["header5"] = "درباره"
        this.FaTexts["header6"] = "ورود"
        this.FaTexts["header7"] = "ثبت نام"
        this.FaTexts["header8"] = "خروج"
        this.FaTexts["header9"] = "داشبورد"
        this.FaTexts["header10"] = "ابولفضل"

        this.FaTexts["home1"] = "گیمـ"
        this.FaTexts["home2"] = "نهمین رویداد بزرگ بازی سازی درخاورمیانه"
        this.FaTexts["home3"] = "این رویداد در مادر دانشگاه های صنعتی کشور برگذار می شود و خیلی نایس است"
        this.FaTexts["home4"] = "7:23:59:2"
        this.FaTexts["home5"] = "تا شروع رویداد"
        this.FaTexts["home6"] = "2289"
        this.FaTexts["home7"] = "شرکت کننده"
        this.FaTexts["home8"] = "برنامه زمانی"
        this.FaTexts["home9"] = "ثبت نام"
        this.FaTexts["home10"] = "1 بهمن 99"
        this.FaTexts["home11"] = "مسابقه"
        this.FaTexts["home12"] = "11 بهمن 99"
        this.FaTexts["home13"] = "داوری"
        this.FaTexts["home14"] = "21 بهمن 99"
        this.FaTexts["home15"] = "کارگاه ها"
        this.FaTexts["home16"] = "کارگاه بازی سازی"
        this.FaTexts["home17"] = "سه شنبه 2 بهمن 99"
        this.FaTexts["home18"] = "11 نفر"
        this.FaTexts["home19"] = "مبتدی"
        this.FaTexts["home20"] = "ثبت نام"
        this.FaTexts["home21"] = "توضیحات"
        this.FaTexts["home22"] = " تاریخ بِیهَقی یا تاریخ مسعودی نام کتابی نوشتهٔ ابوالفضل محمد بن حسین بیهقی است که موضوع اصلی آن تاریخ پادشاهی مسعود غزنوی و دودمان غزنوی است. این کتاب علاوه بر تاریخ غزنویان، قسمت‌هایی دربارهٔ صفاریان، سامانیان و دورهٔ پیش از برآمدن و پادشاهی محمود غزنوی دارد. نسخهٔ اصلی کتاب حدود ۳۰ جلد بوده"
        this.FaTexts["home23"] = "ارائه کنندگان"
        this.FaTexts["home24"] = "مسعود فراستی"
        this.FaTexts["home25"] = "منتقد درجه یک"
        this.FaTexts["home26"] = "تاک ها"
        this.FaTexts["home27"] = "گفتگوی کشور ها"
        this.FaTexts["home28"] = "سه شنبه 2 بهمن 99"
        this.FaTexts["home29"] = "11 نفر"
        this.FaTexts["home30"] = "مبتدی"
        this.FaTexts["home31"] = "ثبت نام"
        this.FaTexts["home32"] = "توضیحات"
        this.FaTexts["home33"] = "تاریخ بِیهَقی یا تاریخ مسعودی نام کتابی نوشتهٔ ابوالفضل محمد بن حسین بیهقی است که موضوع اصلی آن تاریخ پادشاهی مسعود غزنوی و دودمان غزنوی است. این کتاب علاوه بر تاریخ غزنویان، قسمت‌هایی دربارهٔ صفاریان، سامانیان و دورهٔ پیش از برآمدن و پادشاهی محمود غزنوی دارد. نسخهٔ اصلی کتاب حدود ۳۰ جلد بوده"
        this.FaTexts["home34"] = "ارائه کنندگان"
        this.FaTexts["home35"] = "مسعود فراستی"
        this.FaTexts["home36"] = "منتقد درجه یک"
        this.FaTexts["home37"] = "تایتل"
        this.FaTexts["home38"] = "ساب تایتل"
        this.FaTexts["home39"] = "تاریخ بِیهَقی یا تاریخ مسعودی نام کتابی نوشتهٔ ابوالفضل محمد بن حسین بیهقی است که موضوع اصلی آن تاریخ پادشاهی مسعود غزنوی و دودمان غزنوی است. این کتاب علاوه بر تاریخ غزنویان، قسمت‌هایی دربارهٔ صفاریان، سامانیان و دورهٔ پیش از برآمدن و پادشاهی محمود غزنوی دارد. نسخهٔ اصلی کتاب حدود ۳۰ جلد بوده"
        this.FaTexts["home40"] = "حامیان"
        this.FaTexts["home41"] = "حامی"
        this.FaTexts["home42"] = "designed & developed ba eshgh"

        this.FaTexts["dash-event1"] = "ابوالفضل بیهقی"
        this.FaTexts["dash-event2"] = "رویداد ها"
        this.FaTexts["dash-event3"] = "محتوا ها"
        this.FaTexts["dash-event4"] = "وضعیت تیم"
        this.FaTexts["dash-event5"] = "افزودن محتوا"
        this.FaTexts["dash-event6"] = "رویداد ها"
        this.FaTexts["dash-event7"] = "کارگاه ها"
        this.FaTexts["dash-event8"] = "کارگاه بازی سازی"
        this.FaTexts["dash-event9"] = "سه شنبه 2 بهمن 99"
        this.FaTexts["dash-event10"] = "11 نفر"
        this.FaTexts["dash-event11"] = "مبتدی"
        this.FaTexts["dash-event12"] = "ثبت نام"
        this.FaTexts["dash-event13"] = "توضیحات"
        this.FaTexts["dash-event14"] = "تاریخ بِیهَقی یا تاریخ مسعودی نام کتابی نوشتهٔ ابوالفضل محمد بن حسین بیهقی است که موضوع اصلی آن تاریخ پادشاهی مسعود غزنوی و دودمان غزنوی است. این کتاب علاوه بر تاریخ غزنویان، قسمت‌هایی دربارهٔ صفاریان، سامانیان و دورهٔ پیش از برآمدن و پادشاهی محمود غزنوی دارد. نسخهٔ اصلی کتاب حدود ۳۰ جلد بوده"
        this.FaTexts["dash-event15"] = "ارائه کنندگان"
        this.FaTexts["dash-event16"] = "مسعود فراستی"
        this.FaTexts["dash-event17"] = "منتقد درجه یک"
        this.FaTexts["dash-event18"] = "تاک ها"
        this.FaTexts["dash-event19"] = "گفتگوی کشور ها"
        this.FaTexts["dash-event20"] = "سه شنبه 2 بهمن 99"
        this.FaTexts["dash-event21"] = "11 نفر"
        this.FaTexts["dash-event22"] = "مبتدی"
        this.FaTexts["dash-event23"] = "ثبت نام"
        this.FaTexts["dash-event24"] = "توضیحات"
        this.FaTexts["dash-event25"] = "تاریخ بِیهَقی یا تاریخ مسعودی نام کتابی نوشتهٔ ابوالفضل محمد بن حسین بیهقی است که موضوع اصلی آن تاریخ پادشاهی مسعود غزنوی و دودمان غزنوی است. این کتاب علاوه بر تاریخ غزنویان، قسمت‌هایی دربارهٔ صفاریان، سامانیان و دورهٔ پیش از برآمدن و پادشاهی محمود غزنوی دارد. نسخهٔ اصلی کتاب حدود ۳۰ جلد بوده"
        this.FaTexts["dash-event26"] = "ارائه کنندگان"
        this.FaTexts["dash-event27"] = "مسعود فراستی"
        this.FaTexts["dash-event28"] = "منتقد درجه یک"

        this.Texts=this.FaTexts;

    }



}

