

export class Texts{
    FaTexts: { [key: string]: string; }={};
    Texts: { [key: string]: string; }={};

    Init(){
        this.FaTexts["header1"] = "گیمـ"
        this.FaTexts["header2"] = "برنامه زمانی"
        this.FaTexts["header3"] = "کارگاه ها"
        this.FaTexts["header4"] = "تاک ها"
        this.FaTexts["header5"] = "درباره"
        this.FaTexts["header6"] = "ورود"
        this.FaTexts["header7"] = "ثبت نام"
        this.FaTexts["header8"] = "خروج"
        this.FaTexts["header9"] = "داشبورد"
        this.FaTexts["header10"] = "ابولفضل"
        this.FaTexts["header11"] = "شرایط مسابقه"
        this.FaTexts["header12"] = "افراد"

        this.FaTexts["home1"] = "گیمـ کرفت"
        this.FaTexts["home2"] = "نهمین رویداد بزرگ بازی سازی درخاورمیانه"
        this.FaTexts["home3"] = "این رویداد در مادر دانشگاه های صنعتی کشور برگزار می شود و خیلی نایس است"
        this.FaTexts["home4"] = "7:23:59:2"
        this.FaTexts["home5"] = "تا شروع رویداد"
        this.FaTexts["home6"] = "2289"
        this.FaTexts["home7"] = "شرکت کننده"
        this.FaTexts["home8"] = "برنامه زمانی"
        this.FaTexts["home9"] = "ثبت نام"
        this.FaTexts["home10"] = "1 بهمن 99"
        this.FaTexts["home11"] = "تعریف مسابقه"
        this.FaTexts["home12"] = "11 بهمن 99"
        this.FaTexts["home13"] = "داوری"
        this.FaTexts["home14"] = "21 بهمن 99"
        this.FaTexts["home15"] = "کارگاه ها"
        this.FaTexts["home16"] = "کارگاه بازی سازی"
        this.FaTexts["home17"] = "سه شنبه 2 بهمن 99"
        this.FaTexts["home18"] = "نفر"
        this.FaTexts["home19"] = "مبتدی"
        this.FaTexts["home20"] = "ثبت نام"
        this.FaTexts["home21"] = "توضیحات"
        this.FaTexts["home22"] = " تاریخ بِیهَقی یا تاریخ مسعودی نام کتابی نوشتهٔ ابوالفضل محمد بن حسین بیهقی است که موضوع اصلی آن تاریخ پادشاهی مسعود غزنوی و دودمان غزنوی است. این کتاب علاوه بر تاریخ غزنویان، قسمت‌هایی دربارهٔ صفاریان، سامانیان و دورهٔ پیش از برآمدن و پادشاهی محمود غزنوی دارد. نسخهٔ اصلی کتاب حدود ۳۰ جلد بوده"
        this.FaTexts["home23"] = "ارائه کنندگان"
        this.FaTexts["home24"] = "مسعود فراستی"
        this.FaTexts["home25"] = "منتقد درجه یک"
        this.FaTexts["home26"] = "تاک ها"
        this.FaTexts["home27"] = "گفتگوی کشور ها"
        this.FaTexts["home28"] = "سه شنبه 2 بهمن 99"
        this.FaTexts["home29"] = "نفر"
        this.FaTexts["home30"] = "مبتدی"
        this.FaTexts["home31"] = "ثبت نام"
        this.FaTexts["home32"] = "توضیحات"
        this.FaTexts["home33"] = "تاریخ بِیهَقی یا تاریخ مسعودی نام کتابی نوشتهٔ ابوالفضل محمد بن حسین بیهقی است که موضوع اصلی آن تاریخ پادشاهی مسعود غزنوی و دودمان غزنوی است. این کتاب علاوه بر تاریخ غزنویان، قسمت‌هایی دربارهٔ صفاریان، سامانیان و دورهٔ پیش از برآمدن و پادشاهی محمود غزنوی دارد. نسخهٔ اصلی کتاب حدود ۳۰ جلد بوده"
        this.FaTexts["home34"] = "ارائه کنندگان"
        this.FaTexts["home35"] = "مسعود فراستی"
        this.FaTexts["home36"] = "منتقد درجه یک"
        this.FaTexts["home37"] = "تایتل"
        this.FaTexts["home38"] = "ساب تایتل"
        this.FaTexts["home39"] = "تاریخ بِیهَقی یا تاریخ مسعودی نام کتابی نوشتهٔ ابوالفضل محمد بن حسین بیهقی است که موضوع اصلی آن تاریخ پادشاهی مسعود غزنوی و دودمان غزنوی است. این کتاب علاوه بر تاریخ غزنویان، قسمت‌هایی دربارهٔ صفاریان، سامانیان و دورهٔ پیش از برآمدن و پادشاهی محمود غزنوی دارد. نسخهٔ اصلی کتاب حدود ۳۰ جلد بوده"
        this.FaTexts["home40"] = "حامیان"
        this.FaTexts["home41"] = "حامی"
        this.FaTexts["home42"] = "designed & developed ba eshgh"
        this.FaTexts["home43"] = "جوایز مسابقه"
        this.FaTexts["home44"] = "شرایط مسابقه"
        this.FaTexts["home45"] = "تیم اول"
        this.FaTexts["home46"] = "میلیون تومان"
        this.FaTexts["home47"] = "دست اندر کاران"
        this.FaTexts["home48"] = "شرایط مسابقه"
        this.FaTexts["home49"] = "پایان ثبت نام"
        this.FaTexts["home50"] = "11 بهمن 99"
        this.FaTexts["home51"] = "شروع کارگاه ها"
        this.FaTexts["home52"] = "21 بهمن 99"
        this.FaTexts["home53"] = "پایان کارگاه ها"
        this.FaTexts["home54"] = "11 بهمن 99"
        this.FaTexts["home55"] = "تیم دوم"
        this.FaTexts["home56"] = "تیم سوم"
        this.FaTexts["home57"] = "هزینه: "
        this.FaTexts["home58"] = " تومان"
        this.FaTexts["home59"] = "رایگان"



        this.FaTexts["dash-event1"] = "ابوالفضل بیهقی"
        this.FaTexts["dash-event2"] = "رویداد ها"
        this.FaTexts["dash-event3"] = "محتوا ها"
        this.FaTexts["dash-event4"] = "وضعیت تیم"
        this.FaTexts["dash-event5"] = "افزودن محتوا"
        this.FaTexts["dash-event6"] = "رویداد ها"
        this.FaTexts["dash-event7"] = "کارگاه ها"
        this.FaTexts["dash-event8"] = "کارگاه بازی سازی"
        this.FaTexts["dash-event9"] = "سه شنبه 2 بهمن 99"
        this.FaTexts["dash-event10"] = "دیسکورد"
        this.FaTexts["dash-event11"] = "مبتدی"
        this.FaTexts["dash-event12"] = "ورود"
        this.FaTexts["dash-event13"] = "توضیحات"
        this.FaTexts["dash-event14"] = "تاریخ بِیهَقی یا تاریخ مسعودی نام کتابی نوشتهٔ ابوالفضل محمد بن حسین بیهقی است که موضوع اصلی آن تاریخ پادشاهی مسعود غزنوی و دودمان غزنوی است. این کتاب علاوه بر تاریخ غزنویان، قسمت‌هایی دربارهٔ صفاریان، سامانیان و دورهٔ پیش از برآمدن و پادشاهی محمود غزنوی دارد. نسخهٔ اصلی کتاب حدود ۳۰ جلد بوده"
        this.FaTexts["dash-event15"] = "ارائه کنندگان"
        this.FaTexts["dash-event16"] = "مسعود فراستی"
        this.FaTexts["dash-event17"] = "منتقد درجه یک"
        this.FaTexts["dash-event18"] = "تاک ها"
        this.FaTexts["dash-event19"] = "گفتگوی کشور ها"
        this.FaTexts["dash-event20"] = "سه شنبه 2 بهمن 99"
        this.FaTexts["dash-event21"] = "11 نفر"
        this.FaTexts["dash-event22"] = "مبتدی"
        this.FaTexts["dash-event23"] = "ورود"
        this.FaTexts["dash-event24"] = "توضیحات"
        this.FaTexts["dash-event25"] = "تاریخ بِیهَقی یا تاریخ مسعودی نام کتابی نوشتهٔ ابوالفضل محمد بن حسین بیهقی است که موضوع اصلی آن تاریخ پادشاهی مسعود غزنوی و دودمان غزنوی است. این کتاب علاوه بر تاریخ غزنویان، قسمت‌هایی دربارهٔ صفاریان، سامانیان و دورهٔ پیش از برآمدن و پادشاهی محمود غزنوی دارد. نسخهٔ اصلی کتاب حدود ۳۰ جلد بوده"
        this.FaTexts["dash-event26"] = "ارائه کنندگان"
        this.FaTexts["dash-event27"] = "مسعود فراستی"
        this.FaTexts["dash-event28"] = "منتقد درجه یک"
        this.FaTexts["dash-event29"] = "theater_comedy"
        this.FaTexts["dash-event30"] = "perm_media "
        this.FaTexts["dash-event31"] = "groups"
        this.FaTexts["dash-event32"] = "movie"
        this.FaTexts["dash-event33"] = "تیم های رقیب"

        this.FaTexts["error1"] = "error"

        this.FaTexts["cart1"] = "سبد خرید"
        this.FaTexts["cart2"] = "کارگاه بازی سازی"
        this.FaTexts["cart3"] = "سه شنبه 2 بهمن 99"
        this.FaTexts["cart4"] = "2000 تومان"
        this.FaTexts["cart5"] = "حذف"
        this.FaTexts["cart6"] = "10000 تومان"
        this.FaTexts["cart7"] = "پرداخت"
        this.FaTexts["cart8"] = "سبد خرید"

        this.FaTexts["login1"] = "ورود"
        this.FaTexts["login2"] = "گیمـ"
        this.FaTexts["login3"] = "ایمیل"
        this.FaTexts["login4"] = "لطفا یک ایمیل صحیح وارد کنید"
        this.FaTexts["login5"] = "است"
        this.FaTexts["login6"] = "اجباری"
        this.FaTexts["login7"] = "وارد کردن ایمیل"
        this.FaTexts["login8"] = "رمز عبور"
        this.FaTexts["login9"] = "حداقل تعداد کاراکتر های رمز 8 عدد می باشد"
        this.FaTexts["login10"] = "وارد کردن رمز عبور"
        this.FaTexts["login11"] = "ورود"
        this.FaTexts["login12"] = "ثبت نام"
        
        this.FaTexts["signup1"] = "ثبت نام"
        this.FaTexts["signup2"] = "گیمـ"
        this.FaTexts["signup3"] = "نام و نام خانوادگی"
        this.FaTexts["signup4"] = "است"
        this.FaTexts["signup5"] = "اجباری"
        this.FaTexts["signup6"] = "وارد کردن نام"
        this.FaTexts["signup7"] = "ایمیل"
        this.FaTexts["signup8"] = "لطفا یک ایمیل صحیح وارد کنید"
        this.FaTexts["signup9"] = "وارد کردن ایمیل"
        this.FaTexts["signup10"] = "شماره همراه"
        this.FaTexts["signup11"] = "لطفا یک شماره همراه صحیح وارد کنید"
        this.FaTexts["signup12"] = "وارد کردن شماره همراه"
        this.FaTexts["signup13"] = "رمز عبور"
        this.FaTexts["signup14"] = "حداقل تعداد کاراکتر های رمز 8 عدد می باشد"
        this.FaTexts["signup15"] = "وارد کردن رمز عبور"
        this.FaTexts["signup16"] = "ثبت نام"
        this.FaTexts["signup17"] = "ورود"

        this.FaTexts["dash-media1"] = "ابوالفضل بیهقی"
        this.FaTexts["dash-media2"] = "رویداد ها"
        this.FaTexts["dash-media3"] = "محتوا ها"
        this.FaTexts["dash-media4"] = "وضعیت تیم"
        this.FaTexts["dash-media5"] = "افزودن محتوا"
        this.FaTexts["dash-media6"] = "محتوا ها"
        this.FaTexts["dash-media7"] = "کارگاه بازی سازی"
        this.FaTexts["dash-media8"] = "file name"
        this.FaTexts["dash-media9"] = "دانلود"
        this.FaTexts["dash-media10"] = " تاک بازی سازی"
        this.FaTexts["dash-media11"] = "theater_comedy"
        this.FaTexts["dash-media12"] = "perm_media "
        this.FaTexts["dash-media13"] = "groups"
        this.FaTexts["dash-media14"] = "movie"
        this.FaTexts["dash-media15"] = "تیم های رقیب"

        this.FaTexts["people1"] = "افراد"
        this.FaTexts["people2"] = "تیم فنی"
        this.FaTexts["people3"] = "امیررضا بهمنش"
        this.FaTexts["people4"] = "توسعه دهنده ی جلو"
        this.FaTexts["people5"] = "آرین متقی"
        this.FaTexts["people6"] = "Frontend Developer"
        this.FaTexts["people7"] = "حسین لوک زاده"
        this.FaTexts["people8"] = "Backend Developer"
        this.FaTexts["people9"] = "علیرضا آخوندی"
        this.FaTexts["people10"] = "توسعه دهنده ی پشت"
        this.FaTexts["people11"] = "دریا زارع"
        this.FaTexts["people12"] = "هماهنگی سخنرانی ها"
        this.FaTexts["people13"] = "تیم علمی"
        this.FaTexts["people14"] = "هدیه پورقاسم"
        this.FaTexts["people15"] = "هماهنگی سخنرانی ها"
        this.FaTexts["people16"] = "پارسا رحمتی"
        this.FaTexts["people17"] = "برنامه ریزی مسابقه"
        this.FaTexts["people18"] = "دانیال کردمدانلو"
        this.FaTexts["people19"] = "هماهنگی و تیم فنی کارگاه"
        this.FaTexts["people20"] = "علی شکوری راد"
        this.FaTexts["people21"] = "برنامه ریزی مسابقه"
        this.FaTexts["people22"] = "زهرا سالاریان"
        this.FaTexts["people23"] = "برنامه ریزی مسابقه"
        this.FaTexts["people24"] = "امیرحسین کاشانی"
        this.FaTexts["people25"] = "هماهنگی و تیم فنی کارگاه"
        this.FaTexts["people26"] = "اردوان روزخوش"
        this.FaTexts["people27"] = "هماهنگی و تیم فنی کارگاه"
        this.FaTexts["people28"] = "محمدباقر عابدی سقّا"
        this.FaTexts["people29"] = "طراح UI/UX"
        this.FaTexts["people30"] = "کوروش روحی"
        this.FaTexts["people31"] = "نائب دبیر"
        this.FaTexts["people32"] = "تیم برگزاری"
        this.FaTexts["people33"] = "محمدابراهیم ادیب زاده"
        this.FaTexts["people34"] = "دبیر"
        this.FaTexts["people35"] = "پریا مهربد"
        this.FaTexts["people36"] = "نائب دبیر"
        this.FaTexts["people37"] = "فاطمه ولی پور"
        this.FaTexts["people38"] = "همه کاره"
        this.FaTexts["people39"] = "مهران غفاریان"
        this.FaTexts["people40"] = "برندینگ"
        this.FaTexts["people41"] = "تیم برندینگ"
        this.FaTexts["people42"] = "سردسته خلافکارا"
        this.FaTexts["people43"] = "روژین ستارپور"
        this.FaTexts["people44"] = "محمود صانعیان"
        this.FaTexts["people45"] = "عماد فردوسی"

        this.FaTexts["logo1"] = "گیمـ"
        this.FaTexts["logo2"] = "کرفت"

        this.FaTexts["rules1"] = "شرایط مسابقه"
        this.FaTexts["rules2"] = "تایتل"
        this.FaTexts["rules3"] = "تاریخ بِیهَقی یا تاریخ مسعودی نام کتابی نوشتهٔ ابوالفضل محمد بن حسین بیهقی است که موضوع اصلی آن تاریخ پادشاهی مسعود غزنوی و دودمان غزنوی است. این کتاب علاوه بر تاریخ غزنویان، قسمت‌هایی دربارهٔ صفاریان، سامانیان و دورهٔ پیش از برآمدن و پادشاهی محمود غزنوی دارد. نسخهٔ اصلی کتاب حدود ۳۰ جلد بوده"
        this.FaTexts["rules4"] = "ساب تایتل"
        this.FaTexts["rules5"] = "تاریخ بِیهَقی یا تاریخ مسعودی نام کتابی نوشتهٔ ابوالفضل محمد بن حسین بیهقی است که موضوع اصلی آن تاریخ پادشاهی مسعود غزنوی و دودمان غزنوی است. این کتاب علاوه بر تاریخ غزنویان، قسمت‌هایی دربارهٔ صفاریان، سامانیان و دورهٔ پیش از برآمدن و پادشاهی محمود غزنوی دارد. نسخهٔ اصلی کتاب حدود ۳۰ جلد بوده"

        this.FaTexts["dash-teams1"] = "وضعیت تیم"
        this.FaTexts["dash-teams2"] = "افراد تیم"
        this.FaTexts["dash-teams3"] = "برای تشکیل تیم، پس از جستجو و انتخاب افراد ، مبلغ ۱۰۰۰۰۰۰ تومان از طریق درگاه بانکی پرداخت کنید."
        this.FaTexts["dash-teams4"] = "نام تیم"
        this.FaTexts["dash-teams5"] = "وارد کردن نام"
        this.FaTexts["dash-teams6"] = "ایمیل"
        this.FaTexts["dash-teams7"] = "وضعیت تیم"
        this.FaTexts["dash-teams8"] = "وضعیت تیم"
        this.FaTexts["dash-teams9"] = "وضعیت تیم"
        this.FaTexts["dash-teams10"] = "وضعیت تیم"
        this.FaTexts["dash-teams11"] = "وضعیت تیم"

        this.FaTexts["not-found1"] = "۴۰۴"
        this.FaTexts["not-found2"] = "!یافت می نشود"
        this.FaTexts["not-found3"] = "صفحه اصلی"
        this.FaTexts["dash-teams12"] = "وضعیت تیم"
        this.FaTexts["dash-teams12"] = "وضعیت تیم"
        this.FaTexts["dash-teams12"] = "وضعیت تیم"

        this.Texts=this.FaTexts;

    }



}

